import { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@pheralb/toast";
import { QueryProvider } from "@/libs/tanstack-query";

import "./globals.css";

const inter = Inter({
    subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${inter.className} text-zinc-700 antialiased`}>
                <QueryProvider>
                    {children}
                </QueryProvider>

                <Toaster />
            </body>
        </html>
    );
}