import { Toaster } from "@pheralb/toast"
import TanstackQueryProvider from "@/libs/tanstack-query/provider"

import { Metadata } from "next"
import { cn } from "@/libs/utils"
import { Inter } from "next/font/google"

import "./globals.css"

const inter = Inter({
    subsets:['latin'],
    variable:'--font-sans'
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html
            lang="en"
            className={cn("font-sans", inter.variable)}
        >
            <body>
                <Toaster />
                <TanstackQueryProvider>{children}</TanstackQueryProvider>
            </body>
        </html>
    )
}
